'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OMC2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _1053188() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1053188", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _2077164() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2077164", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _2268298() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("2268298", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _4202848() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("4202848", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property _467272() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("467272", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property background4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("background4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_booking_no_logo_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg booking no logo 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_booking_no_logo_21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg booking no logo 21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BG_CAR_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG CAR 3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BG_CAR_31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG CAR 31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BG_CARS_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG CARS 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BG_CARS_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG CARS 4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_darkblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_darkblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_driver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg driver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_history_latest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg history latest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_home_no_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg home no logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_home_no_logo1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg home no logo1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_home_no_logo2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg home no logo2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_home_no_logo3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg home no logo3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_no_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg no logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_pink() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg pink", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_pink1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg pink1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bg_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bg_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BG1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BG1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property bo_young() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bo young", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property BOOK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BOOK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property book_now() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book now", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property booking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("booking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property booooking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("booooking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property button_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("button_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property car_booking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("car booking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Cash_Payment_bro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Cash Payment-bro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CHAEYEONN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHAEYEONN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CHOOSING_CAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHOOSING CAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CHOOSING_CAR1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHOOSING CAR1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property CHOOSING_CAR2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHOOSING CAR2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property complete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("complete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DOYEON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOYEON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DRIVER() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVER", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_bg_book_cheking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver bg book cheking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_bg_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver bg history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_bg_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver bg home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_bg_profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver bg profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_book_checking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver book checking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DRIVER_CHOICE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVER CHOICE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DRIVER_CHOICE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVER CHOICE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver_female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_gif() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver gif", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver_history1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver history1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DRIVER1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVER1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property DRIVER11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DRIVER11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driver31() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driver31", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driverman() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driverman", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property driverrr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("driverrr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property emoji() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("emoji", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FEEDBACK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FEEDBACK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property FELIX() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("FELIX", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property female_driver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("female_driver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Front_car_pana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Front car-pana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property history_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("history_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HISTRY1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HISTRY1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HOME_NO_TITLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HOME NO TITLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property HOME_NO_TITLE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HOME NO TITLE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_arrived_COD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_arrived COD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_arrow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_arrow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_cash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_cash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_currentLocation() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_currentLocation", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_emoji_mad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_emoji_mad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_emoji_mutawasit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_emoji_mutawasit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_fpx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_fpx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_google() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_google", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_onlinebanking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_onlinebanking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_payment() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_payment", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_payment2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_payment2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_smiley() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_smiley", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_tick() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_tick", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property icon_trovapay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icon_trovapay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property JEONGIN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JEONGIN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property johor_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("johor new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property JOSHUA() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("JOSHUA", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property kedah_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kedah ", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property kedah_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kedah new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property kedahh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kedahh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property kelanta_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kelanta new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property kl_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("kl new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property location_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("location_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property location2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("location2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LOG_OUT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOG OUT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LOG_OUT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOG OUT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property LOG_OUT2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LOG OUT2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_booking() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo booking", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_history() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo history", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_home1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo home1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_places() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo places", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_setting() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo setting", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property logo_top_up() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("logo top up", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property male_driver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("male_driver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property moving_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("moving icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property orange_gradient() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("orange gradient", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_dua() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_dua", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_dua1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_dua1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_dua2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_dua2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_empat() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_empat", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_lima() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org lima", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_satu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_satu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property org_tiga() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("org_tiga", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property pahang_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pahang new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PAST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PAST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property penang_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("penang new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property perak_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("perak new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property perlis_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("perlis new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PLACES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLACES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PLACES_NO_TITLE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLACES NO TITLE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property previous() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("previous", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property profile_no_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("profile no title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PROFILE1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PROFILE1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property PURPLE_GRADINET() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PURPLE GRADINET", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property qr_code() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qr code", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property qr_Ewallet() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qr_Ewallet", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property REPORT1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REPORT1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Road_sign_amico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Road sign-amico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property selangor_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selangor new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property setting_no_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("setting no title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Smart_mobility_amico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Smart mobility-amico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property STATUS_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STATUS 2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Successful_purchase_pana() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Successful purchase-pana", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property suuuuzy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("suuuuzy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property TnG_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TnG_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property Top_up_credit_rafiki() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Top up credit-rafiki", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property top_up_no_title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top up no title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property top_up_no_title1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("top up no title1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property trigger() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trigger", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property trovapay() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("trovapay", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property user2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("user2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property userr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property userrr() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("userrr", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property VERNON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VERNON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Public ReadOnly Property WONWOOO() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WONWOOO", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
